### ISSUE TITLE
Crash When Loaded with Quark

### ISSUE THREAD

**Issue by Lonemind** [ephys/mc-fundamental#4]
When Fundamental 2.2.0 for Forge is loaded alongside Quark I get a crash.

I tested with just these two mods installed.

No crash report was generated but here is my console log at the time.

https://pastebin.com/pR3T6eCL

Glancing at the bottom of the log it makes me think Fundamental and Quark are both trying to do something to the Loom menu but I'm no expert at reading logs.

**Comment by Hahahavana** [comment]
Can confirm, have the same issue at the same loading step. Reverting to version 2.10 stopped the crash from happening.

**Comment by ephys** [comment]
Oh interesting, quark already changes the banner layer limit but they forgot to include the BannerDuplicationRecipe (which is the reason I made this feature).

I'll see if we can coexist, if not I'll probably move BannerDuplicationRecipeMixin over to quark and remove it from here

**Comment by ephys** [comment]
Forgot to mention but this has been fixed & released
